import os
import glob

Import ('env')

prefix = env['PREFIX']

source = [os.path.basename(i) for i in glob.glob('*.cpp')]

target = '../paleoserver'

paleoserver = env.Program(target, source)

env.Install(prefix + '/bin', paleoserver)
env.Alias('install', prefix + '/bin')
